swagger: '2.0'
info:
  version: v1
  title: Readify API
  host: readifyapi1.appspot.com 
paths:
  /api/Token:
    get:
      tags:
        - Values
      operationId: ApiTokenGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      responses:
        '200':
          description: Success
          schema:
            type: string
  '/api/Fibonacci/{n}':
    get:
      tags:
        - Values
      operationId: ApiFibonacciByNGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: 'n'
          in: path
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: Success
          schema:
            format: int64
            type: integer
  '/api/ReverseWords/{sentence}':
    get:
      tags:
        - Values
      operationId: ApiReverseWordsBySentenceGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: sentence
          in: query
          required: false
          type: string
      responses:
        '200':
          description: Success
          schema:
            type: string
  '/api/TriangleType/{a}/{b}/{c}':
    get:
      tags:
        - Values
      operationId: ApiTriangleTypeByAByBByCGet
      consumes: []
      produces:
        - text/plain
        - application/json
        - text/json
      parameters:
        - name: a
          in: path
          required: true
          type: integer
          format: int32
        - name: b
          in: path
          required: true
          type: integer
          format: int32
        - name: c
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: Success
          schema:
            type: string
definitions: {}
securityDefinitions: {}
